#!/usr/bin/env python
import configparser
import json
import logging

import click

from datums_warehouse.broker.warehouse import Warehouse

logger = logging.getLogger(__package__)

@click.command()
@click.argument('config', type=click.File('r'))
@click.option('--log-level', type=str, default='warning')
def update_warehouse(config, log_level):
    """Update the warehouse and its packets specified in the given config file"""
    logging.basicConfig(level=getattr(logging, log_level.upper()))
    cfg = configparser.ConfigParser()
    cfg.read_file(config, config.name)
    for sources in [s for s in cfg if s != cfg.default_section]:
        logger.info(f"updating sources: {sources}")
        with open(cfg[sources]['Warehouse'], mode='r') as wc:
            warehouse = Warehouse(json.load(wc))
        pairs = cfg[sources]['Pairs']
        pairs = warehouse.all_packets() if pairs.lower() == "all" else pairs
        for p in pairs:
            warehouse.update(p)


if __name__ == "__main__":
    update_warehouse()
